
export const FILTER = {
    SET_RANGE: "SET_RANGE",
    SET_INDEX: "SET_INDEX",
    SET_ADDRESS: "SET_ADDRESS",
    PICK_ITEM: "PICK_ITEM",
    SEARCH_FILTER: "SEARCH_FILTER",
}

export const LOGIN_FLOW = {
    LOGIN: "LOGIN",
    LOGINING: "LOGINING",
    GET_FIREBASE_TOKEN:"GET_FIREBASE_TOKEN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    LOGIN_FAILD: "LOGIN_FAILD",
    CONFIRM_FAILD: "CONFIRM_FAILD",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT:"LOGOUT"
}

export const APP = {
    INIT_APP: "INIT_APP",
    USER_MOVE: "USER_MOVE",
    LOADING: "LOADING",
    SET_MAP_DATA:"SET_MAP_DATA",
    EXPAND_SENSORS: "EXPAND_SENSORS",
    EXPAND_FACTORYS: "EXPAND_FACTORYS",
    UPDATE_WINDY: "UPDATE_WINDY",
    SET_WIND_CHART: "SET_WIND_CHART",
    CANCEL_UPDATE_WINDY: "CANCEL_UPDATE_WINDY",
    SET_HEATMAP: "SET_HEATMAP",
    START_APP:"START_APP",
    HIT_MARKER: "GET_HEATMAP",
    UPDATE_ERROR: "UPDATE_ERROR",
    FETCH_FAILD: "FETCH_FAILD",
    UPDATE_DATA: "UPDATE_DATA",
    UPLOAD_DATA: "UPLOAD_DATA",
    UPLOAD_FINISH: "UPLOAD_FINISH"
}

export const AUDITOR_MAP = {
    DRAGED_TIME_SLIDER: "DRAGED_TIME_SLIDER",
    SET_MAP_CENTER: "SET_MAP_CENTER",
    SET_PUTTING_PIN: "SET_PUTTING_PIN",
    SET_TRACK: "SET_TRACK",
}


export const LIST = {
    MOVE_TO: "MOVE_TO",
}

